# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb-annotate',
                'doc_host': 'https://MJBishop.github.io',
                'git_url': 'https://github.com/MJBishop/nb-annotate',
                'lib_path': 'nb_annotate'},
  'syms': {'nb_annotate.core': {'nb_annotate.core.foo': ('core.html#foo', 'nb_annotate/core.py')}}}
